config/routes.rb
Rails.application.routes.draw do# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root 'home#index'
  resources :promotions, only: %i[index show new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  validates :name,
            :code,
            :discount_rate,
            :coupon_quantity,
            :expiration_date,
            presence: true
  validates :code, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  def index
    @promotions = Promotion.all
  end

  def show
    @promotion = Promotion.find(params[:id])
  end

  def new
    @promotion = Promotion.new
  end

  def create
    @promotion = Promotion.new(promotions_attr)
    if @promotion.save
      redirect_to @promotion
    else
      render 'new'
    end
  end

  private

  def promotions_attr
    params.require(:promotion).permit(:name, :description, :code, :discount_rate,
                                      :coupon_quantity, :expiration_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Promotion System</h1>
<h3>Boas vindas ao sistema de gestão de promoções</h3>

<%= link_to 'Promoções', promotions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PromotionSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/promotions/index.html.erb
<% if @promotions.any? %>
<dl>
  <% @promotions.each do |promotion| %>
    <dt>Nome</dt>
    <dd><%= link_to promotion.name, promotion_path(id: promotion.id) %></dd>
    <dt>Descrição</dt>
    <dd><%= promotion.description %></dd>
    <dt>Porcentagem de desconto</dt>
    <dd><%= number_to_percentage promotion.discount_rate, precision: 2, separator: ',' %></dd>
    <hr>
  <% end %>
</dl>
<% else %>
  <h2>Nenhuma promoção cadastrada</h2>
<% end %>

<%= link_to 'Voltar', root_path%>
<%= link_to 'Registrar uma promoção', new_promotion_path%>

app/views/promotions/new.html.erb
<h1>Nova Promoção</h1>

<% if @promotion.errors.any? %>
  <p>Não foi possivel criar a promoção</p>
  <p>Confira os erros abaixo:</p>

  <ul>
    <% @promotion.errors.full_messages.each do |m| %>
      <li><%= m %></li>
    <% end %>
  </ul>
<% end %>




<%= form_with(model: @promotion) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  
  <div>
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>
  
  <div>
    <%= f.label :discount_rate %>
    <%= f.text_field :discount_rate %>
  </div>
  
  <div>
    <%= f.label :coupon_quantity %>
    <%= f.text_field :coupon_quantity %>
  </div>
  
  <div>
    <%= f.label :expiration_date %>
    <%= f.text_field :expiration_date %>
  </div>

  <%= f.submit 'Criar promoção' %>

<% end %>

app/views/promotions/show.html.erb
<dl>
  <dt>Nome</dt>
  <dd><%= @promotion.name %></dd>
  <dt>Descrição</dt>
  <dd><%= @promotion.description %></dd>
  <dt>Porcentagem de desconto</dt>
  <dd><%= number_to_percentage @promotion.discount_rate, precision: 2, separator: ',' %></dd>
  <dt>Código</dt>
  <dd><%= @promotion.code %></dd>
  <dt>Data de expiração</dt>
  <dd><%= I18n.localize @promotion.expiration_date %></dd>
  <dt>Quantidade de cupons</dt>
  <dd><%= @promotion.coupon_quantity %></dd>
  <hr>
</dl>

<%= link_to 'Voltar', promotions_path%>